<a href="https://colab.research.google.com/github/CHOCOCHANEL/Data-Analysis/blob/main/Python_(Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy
* NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers.
* In NumPy dimensions are called axes.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, ' type: ', type(arr), ' shape: ', arr.shape)
print('arr.ndim: ', arr.ndim)

[1 2 3 4 5]  type:  <class 'numpy.ndarray'>  shape:  (5,)
arr.ndim:  1


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
print(arr, ' type: ', type(arr), ' shape: ', arr.shape)
print('arr.ndim: ', arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]  type:  <class 'numpy.ndarray'>  shape:  (2, 5)
arr.ndim:  2


#### np.arange
* To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [ ]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

#### Array Layout

* When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
>- the last axis is printed from left to right,
>- the second-to-last is printed from top to bottom,
>- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
b = np.arange(12).reshape(4, 3) #2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
c = np.arange(24).reshape(2, 3, 4) #3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### Flatten
* When using deep learning networks such as CNN(Convolutional Neural Networks), you need to make input data into flattened form.

In [ ]:
a = np.arange(12).reshape(4, 3) #2d array
flattened_a = a.flatten()
print(a)
print(flattened_a)
print(flattened_a.shape, flattened_a.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,) 1


#### Basic Linear Algebra
* `cross`, `dot`, `outer`, `linalg.svd`, `vdot`

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Basic Statistics
* `cov`, `mean`, `std`, `var`

In [ ]:
x = np.zeros((2, 512*512), dtype=np.float64)
x[0, :] = 1.0
x[1, :] = 0.3
x

array([[1. , 1. , 1. , ..., 1. , 1. , 1. ],
       [0.3, 0.3, 0.3, ..., 0.3, 0.3, 0.3]])

In [ ]:
print(np.mean(x))

0.6499999999999986


In [ ]:
print(np.max(x), np.min(x))

1.0 0.3
